#!/usr/bin/env bash
#MISE description="Checkout the latest tag from temporal cloud"

REF=$(cd src/temporalio_cloud_api && git describe --tags `git rev-list --tags --max-count=1`);
(cd src/temporalio_cloud_api && git checkout ${REF})
